
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘9.0’

use_frameworks!


target ‘星星便利店’ do

pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod "SVProgressHUD"
pod 'Alamofire', '~> 3.0'
pod 'SDWebImage', '~>3.7'
pod 'MJRefresh'

end